"use client";

import { useEffect, useRef, useState } from "react";
import { DoneRenderState, ErrorRenderState, IdleRenderState, QueuedRenderState, RenderingState } from "@/components/steps/render/render-states";

type Phase = "idle" | "queued" | "rendering" | "done" | "error";

export default function RenderStep({ onBack }: { onBack: () => void }) {
  const [phase, setPhase] = useState<Phase>("idle");
  const [progress, setProgress] = useState(0);
  const [eta, setEta] = useState("");
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const startRender = () => { setPhase("queued"); setProgress(0); setTimeout(() => { setPhase("rendering"); let percent = 0; timerRef.current = setInterval(() => { percent += Math.random() * 3.5 + 1; if (percent >= 100) { percent = 100; if (timerRef.current) clearInterval(timerRef.current); setTimeout(() => setPhase("done"), 400); } setProgress(Math.min(100, percent)); const remaining = Math.round((100 - percent) / 100 * 38); setEta(remaining > 0 ? `~${remaining}s remaining` : "Finalizing…"); }, 280); }, 1200); };
  useEffect(() => () => { if (timerRef.current) clearInterval(timerRef.current); }, []);
  return <div className="flex flex-col items-center space-y-6 py-4"><div className="w-full max-w-[600px] space-y-6"><div className="space-y-1 text-center"><h1 className="text-xl font-semibold tracking-tight text-slate-900 dark:text-slate-100">Render &amp; Export</h1><p className="text-sm text-slate-500 dark:text-slate-400">Composite overlay cards onto the background video and export the final MP4.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="border-b border-slate-100 px-6 py-5 dark:border-slate-800"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">Render configuration</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Output Format", "MP4 (H.264)"], ["Resolution", "1920 × 1080"], ["Frame Rate", "29.97 fps"], ["Segments", "7 overlay cards"], ["Duration", "30:42"], ["Audio", "Passthrough AAC"]].map(([label, value]) => <div key={label} className="space-y-0.5"><p className="text-[10px] font-medium uppercase tracking-wider text-slate-400 dark:text-slate-500">{label}</p><p className="text-xs font-semibold text-slate-700 dark:text-slate-300">{value}</p></div>)}</div></div><div className="px-6 py-8">{phase === "idle" && <IdleRenderState onRender={startRender} />}{phase === "queued" && <QueuedRenderState />}{phase === "rendering" && <RenderingState progress={progress} eta={eta} />}{phase === "done" && <DoneRenderState onRenderAgain={() => { setPhase("idle"); setProgress(0); }} />}{phase === "error" && <ErrorRenderState onRetry={startRender} />}</div></div>{(phase === "idle" || phase === "done") && <div className="flex items-center justify-center gap-3"><button type="button" onClick={onBack} className="flex items-center gap-1.5 text-sm font-medium text-slate-500 transition-colors hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200">← Back to Sync</button>{phase === "idle" && <><span className="text-slate-300 dark:text-slate-700">·</span><button type="button" onClick={() => setPhase("error")} className="text-sm text-slate-400 transition-colors hover:text-red-500 dark:text-slate-500">Preview error state</button></>}</div>}</div></div>;
}
