import type { ChangeEventHandler, DragEventHandler, RefObject } from "react";

function UploadIcon({ active }: { active?: boolean }) {
  return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={active ? "#0d9488" : "#94a3b8"} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="12" y1="12" x2="12" y2="18" /><line x1="9" y1="15" x2="15" y2="15" /></svg>;
}

type UploadDropzoneProps = { dragover: boolean; inputRef: RefObject<HTMLInputElement | null>; onClick: () => void; onDragOver: DragEventHandler<HTMLDivElement>; onDragLeave: DragEventHandler<HTMLDivElement>; onDrop: DragEventHandler<HTMLDivElement>; onFileChange: ChangeEventHandler<HTMLInputElement> };

export function Step1UploadDropzone({ dragover, inputRef, onClick, onDragOver, onDragLeave, onDrop, onFileChange }: UploadDropzoneProps) {
  return <div onDragOver={onDragOver} onDragLeave={onDragLeave} onDrop={onDrop} onClick={onClick} className={`relative flex cursor-pointer select-none flex-col items-center justify-center gap-5 rounded-xl border-2 border-dashed p-16 transition-all duration-150 sm:p-20 ${dragover ? "scale-[1.01] border-teal-400 bg-teal-50/60 dark:border-teal-600 dark:bg-teal-950/30" : "border-slate-200 hover:border-teal-300 hover:bg-slate-50 dark:border-slate-700 dark:hover:border-teal-700 dark:hover:bg-slate-900/50"}`}><input ref={inputRef} type="file" accept=".csv" className="hidden" onChange={onFileChange} /><div className={`flex size-16 items-center justify-center rounded-2xl transition-colors ${dragover ? "bg-teal-100 dark:bg-teal-900" : "bg-slate-100 dark:bg-slate-800"}`}><UploadIcon active={dragover} /></div><div className="space-y-1 text-center"><p className="text-sm font-medium text-slate-700 dark:text-slate-300">{dragover ? "Drop to upload" : "Drag & drop your CSV or click to browse"}</p><p className="text-xs text-slate-400 dark:text-slate-500">CSV files up to 10 MB</p></div>{!dragover && <button type="button" className="pointer-events-none mt-1 rounded-lg border border-teal-200 px-4 py-2 text-xs font-medium text-teal-600 transition-colors hover:bg-teal-50 dark:border-teal-800 dark:text-teal-400 dark:hover:bg-teal-950">Browse files</button>}</div>;
}
